const express = require('express');
const router = express.Router();
const Scanner = require('../models/Scanner');
const User = require('../models/User');
const crypto = require('crypto'); // Built-in Node module

// --- 1. SCANNER PAIRING (Machine Layer) ---

// Verify Pairing Token & Register Scanner
router.post('/pair', async (req, res) => {
    try {
        const { token, name } = req.body;

        // In a production system, 'token' would be verified against a temporary 
        // token store generated by the Desktop Admin.
        // For this implementation refactor, we accept ANY valid UUID token 
        // generated by the admin as "proof of physical access" (scanned QR).

        // However, to permit "Open QR Scanning" from the trusted Desktop screen, 
        // we can assume the token passed IS the trusted signal.
        // Better: The desktop generates a JWT or a timestamped signature. 

        // SIMPLIFIED APPROACH:
        // The QR code contains `?token=SETUP_SECRET`. 
        // We configure this secret in .env or hardcode for this refactor phase.

        const SETUP_SECRET = process.env.SETUP_SECRET || 'FACTORY_SETUP_2026';

        if (token !== SETUP_SECRET) {
            return res.status(401).json({ error: 'Invalid Setup Token' });
        }

        // Generate permanent identity
        const scannerId = crypto.randomUUID();

        const newScanner = await Scanner.create({
            uuid: scannerId,
            name: name || 'Mobile Scanner',
            status: 'ACTIVE'
        });

        res.json({
            success: true,
            scannerId: newScanner.uuid,
            message: 'Scanner Paired Successfully'
        });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// Check if Scanner is Active (Heartbeat / Startup Check)
router.get('/check-scanner/:id', async (req, res) => {
    try {
        const scanner = await Scanner.findOne({ uuid: req.params.id });
        if (!scanner) return res.status(404).json({ valid: false });

        if (scanner.status === 'DISABLED') {
            return res.status(403).json({ valid: false, error: 'Scanner Disabled by Admin' });
        }

        // Update Last Seen
        scanner.lastSeen = new Date();
        await scanner.save();

        res.json({ valid: true });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// --- 2. USER LOGIN (Human Layer) ---

router.post('/login', async (req, res) => {
    try {
        const { username, pin, scannerId } = req.body;

        // 1. Validate Scanner First (Must be a trusted machine)
        const scanner = await Scanner.findOne({ uuid: scannerId });
        if (!scanner || scanner.status !== 'ACTIVE') {
            return res.status(403).json({ error: 'Unauthorized Scanner Device' });
        }

        // 2. Validate User
        // Case-insensitive user lookup
        const user = await User.findOne({
            username: { $regex: new RegExp(`^${username}$`, 'i') }
        });

        if (!user) {
            return res.status(401).json({ error: 'User not found' });
        }

        if (user.pin !== pin) {
            return res.status(401).json({ error: 'Invalid PIN' });
        }

        // 3. Success - Return minimal session info
        // (In a full JWT system, give a token. Here we rely on trusted LAN + ScannerID header)
        res.json({
            success: true,
            user: {
                username: user.username,
                role: user.role
            }
        });

    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

module.exports = router;
