directories:
  output: setup_release
  buildResources: build
appId: com.srilakshmitextiles.mobile
productName: Prodexa Mobile
asar: true
files:
  - filter:
      - dist/**/*
      - electron-main.cjs
      - preload.cjs
      - icon.png
      - icon.ico
      - package.json
win:
  target:
    - target: nsis
      arch:
        - x64
  icon: icon.ico
  requestedExecutionLevel: requireAdministrator
nsis:
  oneClick: false
  perMachine: true
  allowToChangeInstallationDirectory: true
  allowElevation: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: Prodexa Mobile
  installerIcon: icon.ico
  uninstallerIcon: icon.ico
  installerHeaderIcon: icon.ico
  artifactName: ${productName} Setup ${version}.${ext}
electronVersion: 40.8.2
